name: CI - Build and Test Service

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'staging/4*'
  merge_group:
    types:
      - checks_requested

jobs:
  build-and-test-prod-image:
    name: Build and test production image
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .github/startup-test

    steps:
      - uses: actions/checkout@v4

      - name: Create secrets
        run: |
            mkdir secrets
            echo -n "auth-dev-cookie-key" > secrets/auth_cookie_key
            echo -n "auth-dev-token-key" > secrets/auth_token_key
            echo -n "openslides" > secrets/internal_auth_password
            echo -n "openslides" > secrets/postgres_password

      - name: Build Prod
        uses: Janmtbehrens/OpenSlides/dev/actions/build-service@all-in-one
        with:
          service: auth
          context: prod

      - name: Run prod image
        run: CONTEXT="prod" docker compose up -d

      - name: Wait for auth-service
        run: CONTEXT="prod" docker compose exec -T auth ./wait-for.sh auth:9004

      - name: Test connection
        run: curl -I localhost:9004/system/auth

      - name: Stop prod containers
        run: CONTEXT="prod" docker compose down --volumes

  # This setups and runs the dev/run-tests.sh script
  run-test-script:
    name: Run-tests.sh Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Auth requires both dev and tests context 
      - name: Build Dev
        uses: Janmtbehrens/OpenSlides/dev/actions/build-service@all-in-one
        with:
          service: auth
          context: dev

      - name: Run Test
        uses: Janmtbehrens/OpenSlides/dev/actions/build-and-test-service@all-in-one
        with:
          service: auth