name: CI

on: [push, pull_request]
jobs:
  build-and-test-dev-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build docker prod image
        run: make build-prod

      - name: Run prod image
        working-directory: .github/startup-test
        run: docker-compose up -d

      - name: Wait for auth-service
        working-directory: .github/startup-test
        run: docker-compose exec -T auth ./wait-for.sh auth:9004

      - name: Test connection
        working-directory: .github/startup-test
        run: curl -I localhost:9004/system/auth

      - name: Stop prod containers
        working-directory: .github/startup-test
        run: docker-compose down --volumes

      - name: Run tests
        run: make run-test

      - name: Check prettify
        run: make run-check-prettify

      - name: Check lint
        run: make run-check-lint

      - name: Stop containers
        run: make stop-dev
